CRM/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ems_auth/', include('ems_auth.urls')),
    path('admin/', admin.site.urls),
    path('payroll/', include('payroll.urls')),
    path('leave/', include('leave.urls')),
    path('settings/', include('settings.urls')),
    path('overtime/', include('overtime.urls')),
    path('holidays/', include('holidays.urls')),
    path('', include('employees.urls')),
    path('ems_admin/', include('ems_admin.urls')),
    path('organisationdetails/', include('organisation_details.urls')),
    path('contract2/', include('contract2.urls')),
    path('notification/', include('notification.urls')),
    path('calendar/', include('cal.urls')),
    path('invoice/', include('invoice1.urls')),
    path('crm/', include('crm_app.urls')),
    path('contact/', include('contacts.urls')),
    # path('attendance/', include('attendance.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = 'employees.views.error_404_view'

crm_app/urls.py
from django.urls import path
from . import views

app_name = 'crm_app'

urlpatterns = [
    path('', views.crm_page, name='crm_page'),
    path('add_new_customer', views.add_new_customer, name='add_new_customer'),
    path('e_crm/<int:id>/', views.customer_page, name="customer_page"),
    path('customer_profile_page/<int:customer_id>/', views.customer_profile_page, name="customer_profile_page"),
    path('edit_customer_page/<int:id>/', views.edit_customer_page, name="edit_customer_page"),
    path('edit_customer/<int:id>', views.edit_customer, name="edit_customer"),
    path('msg', views.msg , name="msg"),
    path('delete_customer/<int:id>', views.delete_customer, name='delete_customer' ),
    
    path('add_new_contact/', views.add_new_contact, name='add_new_contact' ),
    path('edit_contact/', views.edit_contact, name='edit_contact' ),

    path('add_new_bank/', views.add_new_bank, name='add_new_bank' ),
    path('edit_bank/', views.edit_bank, name='edit_bank' ),
    path('add_salesmen/', views.add_salesmen, name='add_salesmen' ),
    ]



invoice1/urls.py
from nturl2path import url2pathname
from django.urls import path
from . import views

app_name = 'invoice'


urlpatterns = [
    path('', views.invoicelist, name='invoice'),
    path('edit_invoice/<int:id>', views.edit_invoice, name="edit_invoice"),
    # path('edit_invoice', views.edit_invoice, name='edit_invoice'),
    path('add_invoice', views.CreateInvoice, name='add_invoice'),
    path('invoice_profile_page/<int:id>/', views.invoice_profile_page, name="invoice_profile_page"),
]


invoice1/models.py
from django.db import models
from crm_app.models import Customer
from datetime import date
from crm_app.models import Customer



  

class Invoice(models.Model):

    invoice_no = models.CharField(max_length=200)
    invoice_date = models.DateField(null=True)
    
    #ship to
    s_name = models.CharField(max_length=200)
    s_email = models.EmailField(null=True)
    s_state = models.CharField(max_length=200)
    s_address = models.CharField(max_length=200)
    # Bill to
    b_name = models.CharField(max_length=200)
    b_email = models.EmailField(null=True)
    b_state = models.CharField(max_length=200)
    b_address = models.CharField(max_length=200)
    # placeofsupply'
    Address = models.CharField(max_length=200)
 
    def __str__(self):
        return str(self.invoice_no)

# extra add new
    sub_total = models.CharField(max_length=200,null=True, blank=True,default=None)
    tax_amount = models.CharField(max_length=200,null=True, blank=True,default=None)
    grand_total = models.CharField(max_length=200,null=True, blank=True,default=None)
    amount_deposit = models.CharField(max_length=200,null=True, blank=True,default=None)
    amount_due = models.CharField(max_length=200,null=True, blank=True,default=None)
class Product(models.Model):
    
    invoice_no = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    product = models.CharField(max_length=200,null=True, blank=True,)
    price = models.IntegerField(null=True, blank=True,default=None)
    qty = models.IntegerField(null=True, blank=True,default=None)
    tax = models.IntegerField(null=True, blank=True,default=None)
    total = models.IntegerField(null=True, blank=True,default=None)
    def __str__(self):
        return str(self.invoice_no)


invoice1/views.py
from django.shortcuts import render

# Create your views here.
from invoice1.models import Invoice,Product
from crm_app.models import Customer
from contacts.models import Contact
from .selectors import get_invoice
import datetime
from uuid import uuid4




def invoicelist(request): 

    # customer = Customer.object.all()
    # get_product = Product.objects.all().order_by('-pk')

    context={
        "invoice": Invoice.objects.all(),
        # 'product': get_product,
        # "invoice": "active",
        # "customer" : customer,
    }
    return render(request, 'invoice-table-list.html',context)



def CreateInvoice(request):
    # import pdb
    # pdb.set_trace()
    number = 'INVcd-' + str(uuid4()).split('-')[1]
    
    

    if request.method == 'POST':
        invoice_no = request.POST['invoice_no']
        b_name = request.POST['b_name']
        b_email = request.POST['b_email']
        b_state = request.POST['b_State']
        b_address = request.POST['b_Address']
     
        s_name = request.POST['s_name']
        s_email = request.POST['s_email']
        s_state = request.POST['s_State']
        s_address = request.POST['s_Address']
        
        Address = request.POST['Address']
        invoice_date = request.POST['date']

        #Product
        product = request.POST['product[]']
        price = request.POST['price[]']
        qty = request.POST['qty[]']
        tax = request.POST['tax1']
        total = request.POST['total[]']
        # total amount_0
        sub_total = request.POST['sub_total']
        tax_amount = request.POST['tax_amount']
        grand_total = request.POST['total_amount']
        amount_deposit = request.POST['amount_deposit']
        amount_due = request.POST['amount_due']
        invoice_obj = Invoice(invoice_no=invoice_no,b_name=b_name, b_email=b_email ,b_state=b_state,b_address=b_address,
                              s_name=s_name, s_email=s_email,s_state = s_state,s_address = s_address, invoice_date=invoice_date, Address=Address
                             ,grand_total=grand_total,amount_deposit=amount_deposit, sub_total=sub_total, amount_due=amount_due, tax_amount=tax_amount)
        invoice_obj.save()
        
        
        product_obj = Product( invoice_no=invoice_obj, product=product,price=price,qty=qty,tax=tax,total=total  )
       
        product_obj.save()
    context = {
        'number': number,
        "invoice": "active",

        # 'customer':customer
    }
    return render(request, 'create_invoice.html',context)


# edit invoice pages here

def invoic_edit_pages(request,id):
    inv=Invoice.objects.get(pk=id)
    context = {
        "crm_app":"active",
        "inv":inv
    }
    return render(request,"edit_invoice.html", context)



#for edit pages 
def edit_invoice(request, id):
    number = 'INVcd-' + str(uuid4()).split('-')[1]

    inv=Invoice.objects.get(pk=id)
    inv.invoice_no = request.POST['invoice_no']
    inv.b_name = request.POST['b_name']
    inv.b_email = request.POST['b_email']
    inv.b_state = request.POST['b_State']
    inv.b_address = request.POST['b_Address']
     
    inv.s_name = request.POST['s_name']
    inv.s_email = request.POST['s_email']
    inv.s_state = request.POST['s_State']
    inv.s_address = request.POST['s_Address']
        
    inv.Address = request.POST['Address']
    inv.invoice_date = request.POST['date']

        #Product
    inv.product = request.POST['product[]']
    inv.price = request.POST['price[]']
    inv.qty = request.POST['qty[]']
    inv.tax = request.POST['tax1']
    inv.total = request.POST['total[]']
        # total amount_0
    inv.sub_total = request.POST['sub_total']
    inv.tax_amount = request.POST['tax_amount']
    inv.grand_total = request.POST['total_amount']
    inv.amount_deposit = request.POST['amount_deposit']
    inv.amount_due = request.POST['amount_due']

    if request.method== 'POST':
        inv.save()
        context = {
            "inv":"active",
            "inv": inv,
            "number":number
        }
        return render(request, "success.html", context)
    # else:
    #     context = {
    #         "inv": "active",
    #         "failed_msg": "Failed! You performed a GET request"
    #     }

    #     return render(request, "c/contact_page.html", context)


  

#profile page for this 
def invoice_profile_page(request,   id):
    invoice= Invoice.objects.get(pk=id)
    product = Product.objects.filter(invoice_no=invoice)
    context = {
        "user": request.user,
        "contact": "active",
        "invoice": invoice,
        "product": product,

    }
    return render(request, 'invoice_profile.html', context)


invoice1/templates/create_invoice.html
{%extends 'crm/base.html'%}
{% load static %}
{%block page_title %}  {%endblock%} 
{% block new_script %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <style>
      .row input{
            border-style: none;
             /* font-weight:bold; */
            width:80%;
            font-size: medium;
      }
      .row h2,h3,h4,h5{
          font-weight:bold;
      }
    </style>
    
    {% endblock new_script %}
    {%block content%}

<form action="" method="POST" class="mt-5">
    {% csrf_token %}
    <!------ Include the above in your HEAD tag ---------->

    <div class="container">

    <h2 class="text-center mb-2" style="font-weight:bold;">Tax Invoice</h2>
    <div class="row">
      <div class="col-sm-2">
        <img src="{% static 'assets/img/favicon.png' %}" alt="img" srcset="" style="width: 100%;">
      </div>

        <div class="col-sm-6 bold">
          <h2>PN-HR CONSULTING</h2>
          <h5> Phone: +971-55-4723041</h5>
          <h5> Email: care@pnhrconsulting.com</h5>
          <h5>1646, Damas Tower, Rolla, Sharjah, UAE</h5>
          <h5>Mon-Sunday: 10:00AM - 7:00PM</h5>
        </div>
        <div class="col-sm-4">
          <h5>invoice no.</h5>
            <input type="text" name="invoice_no" value={{number}} placeholder="xxx/xx/x" style="font-size: x-large; width: 100%;" readonly="readonly">
          <h5> Date : <input type="date" name="date" required  {{invoice.invoice_date}}></h5>
        </div>
    </div>


    <div class="row mt-2">
        <div class="col-sm-4">
            <h3 >BILL  TO</h3> <br>
            <h5>Name :  <input type="text" placeholder="xxxxxxxxx" name="b_name"  value= {{invoice.b_name}} ></h5>
            <h5>E-mail : <input type="text" placeholder="xxxxxxxxx" name="b_email" value={{invoice.b_email}}></h5>
            <h5>State :  <input type="text" placeholder="xxxxxxxxx" name="b_State" value={{invoice.b_state}}></h5>
            <b>Address : </b> <br><textarea name="b_Address" id="" cols="30" rows="3" placeholder="xxxx xxxx xxx xxxxxx" style="width: 95%; border-style: none; font-weight:bold;font-size: medium;" {{invoice.b_address}}></textarea>
        </div>
        <div class="col-sm-4">
            <h3 >SHIP TO</h3> <br>
            <h5>Name :<input type="text" placeholder="xxxxxxxxx" name="s_name" value={{invoice.s_name}}></h5>
            <h5>E-mail :<input type="text" placeholder="xxxxxxxxx@gmail.com" name="s_email" value={{invoice.s_email}}></h5>
            <h5>State : <input type="text" placeholder="xxxxxxxxx" name="s_State"  value={{invoice.s_state}}></h5>
         <b>Address : </b> <br>  <textarea name="s_Address" id="" cols="30" rows="3" placeholder="xxxx xxxx xxx xxxxxx" style="width: 95%; border-style: none; font-weight:bold;font-size: medium;" value={{invoice.s_address}}></textarea>
        </div>
        <div class="col-sm-4">
            <h3 >PLACE OF SUPPLY</h3> <br>
            <b>Address : </b> <br>  <textarea name="Address" id="" cols="30" rows="3" placeholder="xxxx xxxx xxx xxxxxx" style="width: 95%; border-style: none; font-weight:bold;font-size: medium;"  value={{invoice.Address}}></textarea>
        </div>
    </div>


      <div class="row clearfix">
        <div class="col-md-12">
          <table class="table table-bordered table-hover" id="tab_logic">
            <thead>
              <tr>
                <th class="text-center"> # </th>
                <th class="text-center"> Product </th>
                <th class="text-center"> Price </th>
                <th class="text-center"> Quantity </th>
                <th class="text-center">TAX</th>
                <th class="text-center"> Total </th>
              </tr>
            </thead>
            <tbody>
              <tr id='addr0'>
                <td>1</td>
                <td><input type="text" name='product[]'  placeholder='Enter Product Name' class="form-control" {{Product.product}}/></td>
                <td><input type="number" name='price[]' placeholder='Enter Unit Price' class="form-control price" step="0.00" min="0" {{product.price}}/></td>
                <td><input type="number" name='qty[]' placeholder='Enter Qty' class="form-control qty" step="0" min="0"   {{product.price}} /></td>
                <td class="text-center"><div class="input-group mb-2 mb-sm-0">
                  <input type="number" class="form-control" id="tax" placeholder="0" name="tax1"  {{product.tax}}>>
                  <div class="input-group-addon">%</div>
                </div></td>
                <td><input type="number" name='total[]' placeholder='0.00' class="form-control total" readonly  {{Product.total}} /></td>
              </tr>
              <tr id='addr1'></tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row clearfix">
        <div class="col-md-12">
          <butto id="add_row" class="btn btn-default pull-left">Add Row</butto>
          <butto id='delete_row' class="pull-right btn btn-default">-</butto>
        </div>
      </div>
      <div class="row clearfix" style="margin-top:20px">
        <div class="col-md-4"></div> <div class="col-md-4"></div>
        <div class="pull-right col-md-4">
          <table class="table table-bordered table-hover" id="tab_logic_total">
            <tbody>
              <tr>
                <th class="text-center">Sub Total</th>
                <td class="text-center"><input type="number" name='sub_total' placeholder='0.00' class="form-control" id="sub_total" readonly/ value={{product.sub_total}}></td>
              </tr>
              <!-- <tr>
                <th class="text-center">TAX</th>
                <td class="text-center"><div class="input-group mb-2 mb-sm-0">
                    <input type="number" class="form-control" id="tax" placeholder="0">
                    <div class="input-group-addon">%</div>
                  </div></td>
              </tr> -->
              <tr>
                <th class="text-center">Tax Amount</th>
                <td class="text-center"><input type="number" name='tax_amount' id="tax_amount" placeholder='0.00' class="form-control" readonly/  value={{product.tax_amount}}></td>
              </tr>
              <tr>
                <th class="text-center">Grand Total</th>
                <td class="text-center"><input type="number" name='total_amount' id="total_amount" placeholder='0.00' class="form-control" readonly/  value={{product.grand_total}}></td>
              </tr>
            </tbody>
          </table>
            <div class="col-sm-6">
                <div class="input-item">
                    <label for="discount-percentage"><b>Amount Deposit :</b></label>
                    <input type="text" id="discount-percentage" name="amount_deposit" class="form-control"   value={{product.amount_deposit}}>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="input-item">
                    <label for="discount-amount"> <b>Due Amount :</b> </label>
                    <input type="text" id="discount-amount" name="amount_due" class="form-control" readonly="readonly"   value={{Product.amount_due}} >
                </div>
            </div>
        </div>
          <br> <br>
           <button type="submit" class="calculate btn btn-primary">calculate</button>
      <div class="row mt-4">
        <div class="col-sm-9">
            <h4><b>Declaration</b></h4>
            <p>We declare that this  invoice the actual price of the <g>                       
              
            </g>oods described and that all particulars are true and correct .</p>
       </div>
       <div class="col-sm-3 mt-5">
           <p>Authorized Signature</p>
       </div>
        
       </div>
    </div>
    <button class="btn btn-primary" value="">save</button>
    <button class="btn btn-primary" onclick="window.print()">Print</button>
    <button class="btn btn-primary" value="">send</button>
      </div>



</form>


 <script>
        const calculate = document.querySelector('.calculate');
        calculate.addEventListener('click', (e) => {
        e.preventDefault();
        const billAmt = document.getElementById('total_amount').value;
        const percentage = document.getElementById('discount-percentage').value;
        const discountAmt = document.getElementById('discount-amount');
        const FinalPay = document.getElementById('pay');
        discountAmt.value = billAmt - percentage;
        FinalPay.value = billAmt - discountAmt.value;
        });
    </script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script>

$(document).ready(function(){
    var i=1;
    $("#add_row").click(function(){b=i-1;
      	$('#addr'+i).html($('#addr'+b).html()).find('td:first-child').html(i+1);
      	$('#tab_logic').append('<tr id="addr'+(i+1)+'"></tr>');
      	i++;
  	});
    $("#delete_row").click(function(){
    	if(i>1){
		$("#addr"+(i-1)).html('');
		i--;
		}
		calc();
	});

	$('#tab_logic tbody').on('keyup change',function(){
		calc();
	});
	$('#tax').on('keyup change',function(){
		calc_total();
	});


});

function calc()
{
	$('#tab_logic tbody tr').each(function(i, element) {
		var html = $(this).html();
		if(html!='')
		{
			var qty = $(this).find('.qty').val();
			var price = $(this).find('.price').val();
			$(this).find('.total').val(qty*price);

			calc_total();
		}
    });
}

function calc_total()
{
	total=0;
	$('.total').each(function() {
        total += parseInt($(this).val());
    });
	$('#sub_total').val(total.toFixed(2));
	tax_sum=total/100*$('#tax').val();
	$('#tax_amount').val(tax_sum.toFixed(2));
	$('#total_amount').val((tax_sum+total).toFixed(2));
}

</script>

{%endblock content%}

invoice1/templates/invoice-table-list.html
{%extends 'crm/base.html'%}
{% load static %}
{%block page_title %} Invoice {%endblock%} 
{% block new_script %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% endblock new_script %}
    {%block content%}
<div class="container-fluid">
    <div class="mt-5">
        <a class="btn btn-primary bg-primary text-white" href="{% url 'invoice:add_invoice' %}" role="button">Create</a>
        <table class="table">
            <thead>
                <tr>
                   
                    <th scope="col">Invoice Number</th>
                    <th scope="col">Bill To</th>
                    <th scope="col">Ship To</th>              
                    <th scope="col">Total</th>
                    <th scope="col">Deposit</th>
                    <th scope="col">Due</th>
                  
                    <th scope="col">View</th>

   

                </tr>
            </thead>
            <tbody>
                {% if invoice %}
            {% for x in invoice %}
                <tr>
                   {% comment %} <td>{{invoice}}</td> {% endcomment %}
                    <td scope="col">{{x.invoice_no}}</td>
                    <td scope="col">{{x.b_name}}</td>
                    <td scope="col">{{x.s_name}}</td>
                    <td sc ope="col">{{x.grand_total}}</td>
                    <td scope="col">{{x.amount_deposit}}</td>
                    <td scope="col">{{x.amount_due}}</td>
                   
                    <td scope="col"><a href="{% url 'invoice:invoice_profile_page' x.id %}">View</a></td>

                </tr>

            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

{%endblock content%}

invoice1/templates/invoice.html
{% extends 'crm/base.html' %}

{% block content %}

<br>
<br>
<br>
<h2 class="ml-5">  Unser Construction</h2>

{% endblock %}

invoice1/templates/success.html
{% extends 'crm/base.html'%} {% load static %}
{% block page_title %}
Success!!
{% endblock %}


{% block content %}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3 style="padding-top:20px">{{success_msg}}</h3>
                <a href="{% url 'crm_app:crm_page'%}">
                    <button class="btn btn-outline-danger">Back</button>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}