CRM/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ems_auth/', include('ems_auth.urls')),
    path('admin/', admin.site.urls),
    path('payroll/', include('payroll.urls')),
    path('leave/', include('leave.urls')),
    path('settings/', include('settings.urls')),
    path('overtime/', include('overtime.urls')),
    path('holidays/', include('holidays.urls')),
    path('', include('employees.urls')),
    path('ems_admin/', include('ems_admin.urls')),
    path('organisationdetails/', include('organisation_details.urls')),
    path('contract2/', include('contract2.urls')),
    path('notification/', include('notification.urls')),
    path('calendar/', include('cal.urls')),
    path('invoice/', include('invoice1.urls')),
    path('crm/', include('crm_app.urls')),
    path('contact/', include('contacts.urls')),
    # path('attendance/', include('attendance.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = 'employees.views.error_404_view'

cal/urls.py

from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('index/$', views.index, name='index'),
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/$', views.event, name='event_new'),
	path('event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

contacts/urls.py
from django.urls import path
from  . import views
from django.conf import settings  
from django.conf.urls.static import static  


app_name = 'contact'


urlpatterns = [
    path('', views.contact_page, name ="contact_page"),
    
    path('edit_contact_page/<int:id>/', views.edit_contact_page, name="edit_contact_page"),
    path('edit_contact/<int:id>', views.edit_contact, name="edit_contact"),
    path('contact_profile_page/<int:contact_id>/', views.contact_profile_page, name="contact_profile_page"),
    #process
    path('add_new_contact/', views.add_new_contact, name='add_new_contact'),
    path('delete_contact/<int:id>/', views.delete_page, name="delete_contact"),
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

employees/urls.py
from django.urls import path, reverse
from . import views
app_name = 'employee'
urlpatterns = [
    # Pages
    path('', views.dashboard_page, name="dashboard_page"),
    path('employees/', views.employees_page, name="employees_page"),
    path('employee/<int:id>/', views.employee_page, name="employee_page"),
    path('edit_employee_page/<int:id>/', views.edit_employee_page, name="edit_employee_page"),
    path('edit_certification_page/<int:id>/', views.edit_certification_page, name="edit_certification_page"),
    path('edit_emergency_contact_page/<int:id>/', views.edit_emergency_contact_page,
         name="edit_emergency_contact_page"),
    path('edit_beneficiary_page/<int:id>/', views.edit_beneficiary_page, name="edit_beneficiary_page"),
    path('edit_spouse_page/<int:id>/', views.edit_spouse_page, name="edit_spouse_page"),
    path('edit_dependant_page/<int:id>/', views.edit_dependant_page, name="edit_dependant_page"),

    # Process
    path('add_new_employee/', views.add_new_employee, name="add_new_employee"),
    path('delete_employee/<int:id>', views.delete_employee, name="delete_employee"),
    path('edit_employee/<int:id>', views.edit_employee, name="edit_employee"),
    path('add_new_home_address/', views.add_new_home_address, name="add_new_home_address"),
    path('edit_home_address/', views.edit_home_address, name="edit_home_address"),
    path('add_certification/', views.add_certification, name="add_certification"),
    path('delete_certification/<int:id>', views.delete_certification, name="delete_certification"),
    path('edit_certification/', views.edit_certification, name="edit_certification"),
    path('add_emergency_contact', views.add_emergency_contact, name="add_emergency_contact"),
    path('delete_emergency_contact/<int:id>', views.delete_emergency_contact, name="delete_emergency_contact"),
    path('edit_emergency_contact', views.edit_emergency_contact, name="edit_emergency_contact"),
    path('add_beneficiary/', views.add_beneficiary, name="add_beneficiary"),
    path('edit_beneficiary/', views.edit_beneficiary, name="edit_beneficiary"),
    path('delete_beneficiary/<int:id>/', views.delete_beneficiary, name="delete_beneficiary"),
    path('add_spouse/', views.add_spouse, name="add_spouse"),
    path('edit_spouse/', views.edit_spouse, name="edit_spouse"),
    path('delete_spouse/<int:id>', views.delete_spouse, name="delete_spouse"),
    path('add_dependant/', views.add_dependant, name="add_dependant"),
    path('edit_dependant/', views.edit_dependant, name="edit_dependant"),
    path('delete_dependant/<int:id>', views.delete_dependant, name="delete_dependant"),
    path('add_employee_contacts/', views.add_employee_contacts, name="add_employee_contacts"),
    path('delete_employee_contact/', views.delete_employee_contact, name="delete_employee_contact"),

    path('add_statutory_deduction/', views.add_statutory_deduction, name="add_statutory_deduction"),
    path('edit_statutory_deduction/', views.edit_statutory_deduction, name="edit_statutory_deduction"),
    path('add_deduction/', views.add_deduction, name="add_deduction"),
    path('edit_deduction/', views.edit_deduction, name="edit_deduction"),
    path('add_allowance/', views.add_allowance, name="add_allowance"),
    path('add_supervisee/', views.add_supervisee, name="add_supervisee"),
    path('delete_superviser/<int:id>/', views.delete_supervisee, name="delete_supervisee"),
    path('delete_deduction/<int:id>', views.delete_deduction, name="delete_deduction"),
    path('delete_allowance/<int:id>', views.delete_allowance, name="delete_allowance"),
    path('edit_bank_details/', views.edit_bank_details, name="edit_bank_details"),
    path('add_bank_details/', views.add_bank_details, name="add_bank_details"),
    path('add_organisation_details/', views.add_organisation_details, name="add_organisation_details"),
    path('edit_organisation_details/', views.edit_organisation_details, name="edit_organisation_details"),
    path('employees_download/', views.employees_download, name="employees_download"),
    path('employees_financial_csv/', views.employees_financial_csv, name="employees_financial_csv"),

    path('add_leave_record/', views.add_leave_record, name="add_leave_record"),
    path('edit_leave_record/', views.edit_leave_record, name="edit_leave_record"),
    path('suspend_employee/<int:employee_id>/', views.suspend_employee, name="suspend_employee"),
    path('employee_profile_page/<int:employee_id>/', views.employee_profile_page, name="employee_profile_page"),
    path('add_more_details_page/<int:employee_id>/', views.add_more_details_page, name="add_more_details_page"),
    path('activate_employees_page', views.activate_employees_page, name="activate_employees_page"),
    path('activate_employee/<int:employee_id>/', views.activate_employee, name="activate_employee"),
]


# JS routes
def javascript_settings():
    js_conf = {
        'add_employee_contacts': reverse('add_employee_contacts'),
        'delete_employee_contact': reverse('delete_employee_contact'),
    }

    return js_conf

contacts/models.py
from contextlib import nullcontext
from secrets import choice
from xmlrpc.client import Boolean
from django.db import models
from django_countries.fields import CountryField
from django.core.validators import RegexValidator
from imagefield.fields import ImageField
from datetime import date
# Create your models here.


SO_DO_CHOICE = (
    ('Son Of' , 'S/O'),
    ('Doughter Of' , 'D/O'),
)

BOOLEB = (
    ('True', 'T'),
    ('False', 'F'),
)

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)


class Contact(models.Model):
    img = ImageField(upload_to='contact/', auto_add_fields=True, blank=True)
    f_name = models.CharField(max_length=50)
    l_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=250)
    gender = models.CharField(max_length=20)
    per_address = models.CharField(max_length=250)
    pr_country = CountryField()
    cor_address = models.CharField(max_length=250)
    cr_country = CountryField()
    tax_id = models.CharField(max_length=150)
    date_of_birth = models.DateField()
    Age = models.IntegerField()
    high_education = models.CharField(max_length=250)
    occupation = models.CharField(max_length=150)
    no_of_experience = models.IntegerField()
    parent_f_name = models.CharField(max_length=50)
    parent_l_name = models.CharField(max_length=50)
    pas_no = models.CharField(max_length=16)
    pas_country = CountryField()
    telephone = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    telephone = models.CharField(validators=[telephone], max_length=17, blank=True) # Validators should be a list
    # indivisual = models.BooleanField(default=True, blank=True, null=True, choices=BOOLEB)
    # company = models.BooleanField(default=False, blank=True, null=True , choices=BOOLEB)
    # company_n = models.CharField(max_length=250, blank=True)
    # job_position = models.CharField(max_length=250, blank=True)
    
    def __str__(self):
        return self.f_name + " " + self.l_name










contacts/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput, ImageField
from django_countries.fields import CountryField

from .models import Contact

class DateInput(forms.DateInput):
    input_type = 'date'



class ContactForm(forms.ModelForm):
    class Meta:
      model=Contact
      fields="__all__"

      widgets = {
            'date_of_birth': DateInput()
        }

      # widgets = {

      #   'img': ImageField(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'Name'
      #           }),
      #   'f_name': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'f_name'
      #           }),

      #   'l_name': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'l_name'
      #           }),
      #   'email': EmailInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'Name'
      #           }),
      #   'gender': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'gender'
      #           }),
      #   'per_address': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'per_address'
      #           }),
      #   'pr_country': CountryField(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'pr_country'
      #           }),
      #   'cor_address': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'cor_address'
      #           }),
      #   'cr_country': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'Name'
      #           }),
      #   'tax_id': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'Name'
      #           }),
      #   'f_name': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'Name'
      #           }),
      #   'f_name': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'Name'
      #           }),
      #   'f_name': TextInput(attrs={
      #           'class': "form-control",
      #           'style': 'm ax-width: 300px;',
      #           'placeholder': 'Name'
      #           }),
              
      # }

contacts/views.py
from ast import Return
from django.shortcuts import redirect, render
from ems_auth.models import User
from .models import Contact
from django import forms
from django.http import HttpResponseRedirect
from .services import create_contact
from django.urls import reverse
from django_countries.fields import CountryField
from django.http import HttpResponseRedirect,HttpResponse
from .forms import ContactForm
# Create your views here.
# contact = Contact.objects.all()

# def contact_page(request):
#     form=ContactForm(request.POST)

#     country = CountryField()
#     context = {

#         "contact":contact,
#         "contact_page":"active",
#         "form":form,
#     }

#     return render(request, 'contact/contact_page.html', context)




def contact_page(request):
    country = CountryField()
    contact_get = Contact.objects.all()
    form=ContactForm(request.POST)
    context = {

        "contact":contact_get,
        "contact_page":"active",
        "country":country,
        "form":form,

    }

    return render(request, 'contact/contact_page.html', context)





# this factions will work add new data and show data from the add

def add_new_contact(request):    
    if request.method == 'POST':
        contact = create_contact(request)
        context = {
            "contact_page": "active",
            "success_msg": "You have successfully added %s to the contact" % contact.f_name,
            "contact": contact
        }
        return render(request, 'contact/success.html', context)

    else:
        context = {
            "contact_page": "active",
            "failed_msg": "Failed! You performed a GET request"
        }

        return render(request, "contact/contact_page.html", context)







def edit_contact_page(request, id):
    contact = Contact.objects.get(pk=id)
    context = {
        "contact": "active",
        "contact": contact
 
      
    }
    return render(request, 'contact/edit_contact.html', context)


def edit_contact(request, id):
    contact = Contact.objects.get(pk=id)
    contact.title = request.POST['title']
    contact.f_name = request.POST['f_name']
    contact.l_name = request.POST['l_name']
    contact.email = request.POST['email']
    contact.telephone = request.POST['telephone']
    contact.gender = request.POST['gender']
    contact.date_of_birth = request.POST['date_of_birth']
    contact.per_address = request.POST['per_address']
    contact.pr_country = request.POST['pr_country']
    contact.cor_address = request.POST['cor_address']
    contact.cr_country = request.POST['cr_country']
    contact.Age = request.POST['Age']
    contact.tax_id = request.POST['tax_id']
    contact.high_education = request.POST['high_education']
    contact.occupation = request.POST['occupation']
    contact.no_of_experience = request.POST['no_of_experience']
    contact.parent_f_name = request.POST['parent_f_name']
    contact.parent_l_name = request.POST['parent_l_name']
    contact.pas_no = request.POST['pas_no']
    contact.pas_country = request.POST['pas_country']
    contact.telephone = request.POST['telephone']


    if request.method == 'POST':
        # Fetching data from the add new employee form
        contact.save()
        context = {
            "contact": "active",
            "success_msg": "You have successfully updated %s's bio data" % (contact.f_name),
            "contact": contact,
        }

        return render(request, 'contact/success.html', context)
    else:
        context = {
            "contact": "active",
            "failed_msg": "Failed! You performed a GET request"
        }

        return render(request, "contact/contact_page.html", context)

def contact_profile_page(request, contact_id):
    
    contact = Contact.objects.get(pk=contact_id)



    
    context = {
        "user": request.user,
        "contact": "active",
        "contact": contact,
    }

    return render(request, 'contact/contact_profile.html', context)



def delete_page(request,id):
    pi=Contact.objects.get(id=id)
    pi.delete()
   
    return redirect('/contact')



contacts/templates/contact/contact_page.html
{% extends 'crm/base.html' %} {% block page_title %} Manage Contact
<script>
    $(document).ready(function() {
        $("#search_input").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#contact-table tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
{% block new_script %}



<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{% endblock new_script %}
{% endblock %} {% block content %}
<div class="content">
    <div class="container-fluid">
        <!-- Button trigger modal-->
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal_add_new_contact">
      Add New Contact +
    </button>
  {% comment %} {% load crispy_forms_filters %} {% endcomment %}
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {%if contact %}
                    <h3 style="text-align:center;">Contact</h3>
                    <hr>
                    <div class="table-responsive">
                        <div class="form-group ">
                            <i class="fas fa-search " aria-hidden="true"></i>
                            <input id="search_input" type="text" class="form-control" placeholder="Search....">
                        </div>
                        <table class="table table-hover text-center">
                            <thead class="thead-dark">
                                <th>Name</th>
                                <th>Email</th>
                                <th>Number</th>
                                <th>Gender</th>
                                <th>Action</th>
                                <th></th>
                            </thead>
                            <tbody id="contact-table">
                                {% for contact in contact %}
                                <tr class="text-center">
                                    <td>{{contact}} </td>
                                    
                                    <td>{{contact.email}}</td>
                                    <td>{{contact.telephone}}</td>
                                    <td>{{contact.gender}}</td>
                                    <td>
                                        <a href="{% url 'contact:edit_contact_page' contact.id %}" style="color:inherit">
                    Edit
                  </a> |
                                        <a href="{% url 'contact:contact_profile_page' contact.id %}" style="color:inherit">
                    Profile
                  </a> |
                  <a href="{% url 'contact:delete_contact' contact.id %}" style="color: inherit" ... onclick="return confirm('Are you sure you want to suspend {{contect.f_name}} {{employee.l_name}}?')">
                    delete
                  </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <a href=" {% url 'contact:contact_page' %} " download>
                            <button class="btn btn-outline">Export CSV Report</button>
                        </a>
                    </div>

                    {%else%}

                    

                    {%endif%}
                </div>
            </div>
        </div>


        <!-- Modal: modalAddNewContact -->
        <div class="modal fade" id="modal_add_new_contact" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="overflow-y: auto !important">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <!--Header-->
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">Add Contact </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
                    </div>
                    <!--Body-->
                    <div class="modal-body" id="modalbody">
                       
                            <form action="{%url 'contact:add_new_contact'%}" method="post">
                                {% load crispy_forms_filters %}
                                {%csrf_token%}
                                {{ form|crispy }}
                            
                                <input type="submit" value="Submit">
                              </form>
                            
                </div>
            </div>
        </div>
        <!-- Modal: modalAddNewEmployee -->

    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script>
        let customRadioInline1 = document.getElementById("customRadioInline1")
        let individual = document.getElementById("form-individual")
        let individual1 = document.getElementById("individual1")
        let modalBody = document.getElementById("modalbody")
        
        customRadioInline1.addEventListener('click', () => {
            individual.style.display = "block"
            // modalBody.style.display = "none"
            // individual1.style.display= "none"
        })
        customRadioInline2.addEventListener('click', () => {
            individual.style.display= "none" 
        })
    </script>
    
</div>
{%endblock content%}

contacts/templates/contact/failed.html
{%extends './base.html'%} {%load static %}
{%block page_title %}
Failed!!
{%endblock%}


{% block content %}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3 style="padding-top:20px">{{failed_msg}}</h3>
                <a href="{%url 'employee:employees_page'%}">
                    <button class="btn btn-outline-danger">Back</button>
                </a>
            </div>
        </div>

    </div>
</div>

{%endblock content%}

contacts/templates/contact/success.html
{% extends 'crm/base.html'%} {% load static %}
{% block page_title %}
Success!!
{% endblock %}


{% block content %}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3 style="padding-top:20px">{{success_msg}}</h3>
                <a href="{% url 'contact:contact_page'%}">
                    <button class="btn btn-outline-danger">Back</button>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}