CRM/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ems_auth/', include('ems_auth.urls')),
    path('admin/', admin.site.urls),
    path('payroll/', include('payroll.urls')),
    path('leave/', include('leave.urls')),
    path('settings/', include('settings.urls')),
    path('overtime/', include('overtime.urls')),
    path('holidays/', include('holidays.urls')),
    path('', include('employees.urls')),
    path('ems_admin/', include('ems_admin.urls')),
    path('organisationdetails/', include('organisation_details.urls')),
    path('contract2/', include('contract2.urls')),
    path('notification/', include('notification.urls')),
    path('calendar/', include('cal.urls')),
    path('invoice/', include('invoice1.urls')),
    path('crm/', include('crm_app.urls')),
    path('contact/', include('contacts.urls')),
    # path('attendance/', include('attendance.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = 'employees.views.error_404_view'

contacts/urls.py
from django.urls import path
from  . import views
from django.conf import settings  
from django.conf.urls.static import static  


app_name = 'contact'


urlpatterns = [
    path('', views.contact_page, name ="contact_page"),
    
    path('edit_contact_page/<int:id>/', views.edit_contact_page, name="edit_contact_page"),
    path('edit_contact/<int:id>', views.edit_contact, name="edit_contact"),
    path('contact_profile_page/<int:contact_id>/', views.contact_profile_page, name="contact_profile_page"),
    #process
    path('add_new_contact/', views.add_new_contact, name='add_new_contact'),
    path('delete_contact/<int:id>/', views.delete_page, name="delete_contact"),
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

crm_app/urls.py
from django.urls import path
from . import views

app_name = 'crm_app'

urlpatterns = [
    path('', views.crm_page, name='crm_page'),
    path('add_new_customer', views.add_new_customer, name='add_new_customer'),
    path('e_crm/<int:id>/', views.customer_page, name="customer_page"),
    path('customer_profile_page/<int:customer_id>/', views.customer_profile_page, name="customer_profile_page"),
    path('edit_customer_page/<int:id>/', views.edit_customer_page, name="edit_customer_page"),
    path('edit_customer/<int:id>', views.edit_customer, name="edit_customer"),
    path('msg', views.msg , name="msg"),
    path('delete_customer/<int:id>', views.delete_customer, name='delete_customer' ),
    
    path('add_new_contact/', views.add_new_contact, name='add_new_contact' ),
    path('edit_contact/', views.edit_contact, name='edit_contact' ),

    path('add_new_bank/', views.add_new_bank, name='add_new_bank' ),
    path('edit_bank/', views.edit_bank, name='edit_bank' ),
    path('add_salesmen/', views.add_salesmen, name='add_salesmen' ),
    ]



crm_app/forms.py
from dataclasses import field
from django import forms

from .models import  Customer
# from contact import forms



class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"



# class ContactForm(forms.ModelForm):
#     class Meta:
#       model= Add_more_detail
#       fields="__all__"





# from .models import Contact


# class ContactForm(forms.ModelForm):
#     class Meta:
#       model=Contact
#       fields="__all__"





        

crm_app/views.py
from email import message
from multiprocessing import context
import re
from django.shortcuts import get_object_or_404, render,redirect
from crm_app.models import Customer, Allowance, CustomerDetails, CustomerBankDetail, CustomerSupervision
from employees.models import Employee
from employees.views import employee_page
from settings.selectors import get_all_currencies
from .selectors import get_customer, get_customer_suspect, get_passive_customer, get_customer_prospect, get_customer_approch, get_customer_won, get_customer_negotiate
from crm_app.services import create_customer_instance
from leave.forms.leave_record import LeaveRecordForm
from datetime import date
from organisation_details.models import Department, Position, Team, OrganisationDetail
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView
from contacts.models import Contact 
from .forms import CustomerForm

# Create your views here.


def crm_page(request):
    all_currencies = get_all_currencies()
    form = CustomerForm()
    context = {
        "user": request.user,
        "form":form,
        "currencies": all_currencies,
        "crm_app": "active",
        "customers_suspect": get_customer_suspect,
        "customers_prospect": get_customer_prospect,
        "customers_approch": get_customer_approch,
        "customers_negotiate": get_customer_negotiate,
        "customers_won": get_customer_won,
        "customers": Customer


    }
    return render(request, 'crm_app.html', context)


def add_new_customer(request):
    if request.method == 'POST':
        customer = create_customer_instance(request)
        context = {
            "crm_app": "active",
            "success_msg": "You have successfully added %s to the customer" % customer.first_name,
            "customer": customer
        }

        return render(request, 'success.html', context)

    else:
        context = {
            "crm_app": "active",
            "failed_msg": "Failed! You performed a GET request"
        }

        return render(request, "employees/failed.html", context)

def customer_page(request, id):
    
    employee = Employee.objects.get(pk=id)
    customer = Customer.objects.get(pk=id)
    yr = date.today().year


    context = {
        "user": request.user,
        
        "crm_app": "active",
        "customer": customer,
        "certifications": employee.certification_set.all(),
        "emergency_contacts": employee.emergencycontact_set.all(),
        "beneficiaries": employee.beneficiary_set.all(),
        "spouses": employee.spouse_set.all(),
        "dependants": employee.dependant_set.all(),
        "deps": Department.objects.all(),
        "titles": Position.objects.all(),
        "teams": Team.objects.all(),
        "allowances": Allowance.objects.all(),
   
    }
    return render(request, 'employees/employee.html', context)


from cal.forms import EventForm
from cal.models import Event

def customer_profile_page(request, customer_id):
    instance = Event()
    customer = get_customer(customer_id)
    status = customer.status


    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    context = {
        "user": request.user,
        "crm_app": "active",
        "customer": customer,
        "form" : form
    }

    return render(request, 'customer_profile.html', context)


def status_active(status):
    if status == ['suspect']:
        suspect = ["active"]
        return suspect
    
    elif status == ['prospect']:
        prospect = ["active"]
        return prospect
    
    elif status == ['approch']:
        approch = ["active"]
        return approch
    
    elif status == ['negotiate']:
        negotiate = ["active"]
        return negotiate
    elif status == ['won']:
        won = ["active"]
        return won





def edit_customer_page(request, id):
    customer = Customer.objects.get(pk=id)
    form = CustomerForm()
    context = {
        "form":form,
        "crm_app": "active",
        "customer": customer,
 
      
    }
    return render(request, 'edit_customer.html', context)


def edit_customer(request, id):

    obj = Customer.objects.get(pk=id)


    if request.method == 'POST':
        # Fetching data from the add new employee form
        customer = Customer.objects.get(pk=id)
        customer.title = request.POST['title']
        customer.first_name = request.POST['first_name']
        customer.last_name = request.POST['last_name']
        customer.email = request.POST['email']
        customer.telephone = request.POST['telephone']
        customer.status = request.POST['status']
        # customer.date_of_birth = request.POST['date_of_birth']
        # customer.c_age = request.POST['c_age']
        # customer.education = request.POST['education']
        # customer.occupation = request.POST['occupation']
        # customer.no_of_experience = request.POST['no_of_experience']
        # customer.permanent_address = request.POST['permanent_address']
        # customer.company = request.POST['company']
        # customer.apply_company = request.POST['apply_company']
        # customer.passport_no = request.POST['passport_no']
        # customer.service_type = request.POST['service_type']
      
        # customer.salesperson = request.POST['salesperson']
    

        # Saving the employee instance
        customer.save()
        context = {
            "crm_app": "active",
            "success_msg": "You have successfully updated %s's bio data" % (customer.first_name),
            "customer": customer,
            "obj":obj
        }

        return render(request, 'success.html', context)



    else:
        context = {
            "crm_app": "active",
            "failed_msg": "Failed! You performed a GET request"
        }

        return render(request, "failed.html", context)


def edit_more_details(request,id):
    customer = get_customer(id)
    if request.method == 'POST':
        f_name = request.POST.get('f_name')
        l_name =request.POST.get('l_name')
        email = request.POST.get('Email') 
        gender =request.POST.get('Gender')
        per_address = request.POST.get('Permonent_Address')
        pr_country = request.POST.get('Parrment_Country')
        cor_address = request.POST.get('Current_Address')
        cr_country = request.POST.get('Current_Country')
        tax_id =request.POST.get('Tax_ID')
        date_of_birth = request.POST.get('dob')
        Age = request.POST.get('Age')
        high_education = request.POST.get('high_education')
        occupation = request.POST.get('Occupation')
        no_of_experience =request.POST.get('no_of_experience')
        parent_f_name = request.POST.get('parent_f_name')
        parent_l_name = request.POST.get('parent_l_name')
        pas_no = request.POST.get('passport_number')
        pas_country = request.POST.get('Passport_Country')
        telephone = request.POST.get('Telephone')
    
        obj= Contact(f_name=f_name, l_name=l_name,email=email,gender=gender,per_address=per_address,pr_country=pr_country,cor_address=cor_address,cr_country=cr_country,tax_id=tax_id, date_of_birth=date_of_birth,Age=Age,high_education=high_education,occupation=occupation,no_of_experience=no_of_experience,parent_f_name=parent_f_name,parent_l_name=parent_l_name,pas_no=pas_no, pas_country=pas_country,telephone=telephone)

        obj.save()
        


    context = {
        "user": request.user,
        "crm_page": "active",
        "customer": customer,
    }
    return render(request,"z.html", context)  

import requests
def send_message_on_whatsapp(mobile):

    url = "https://YOUR-WATI-ENDPOINT/api/v1/sendSessionMessage/"+mobile

    headers = {"Authorization":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJhODMwMWYxOC0zZDJiLTQwZWQtOTBjZS1hNmVlY2NkOWFjNGYiLCJ1bmlxdWVfbmFtZSI6InBuaHJpbW1pdWFlQGdtYWlsLmNvbSIsIm5hbWVpZCI6InBuaHJpbW1pdWFlQGdtYWlsLmNvbSIsImVtYWlsIjoicG5ocmltbWl1YWVAZ21haWwuY29tIiwiYXV0aF90aW1lIjoiMDMvMzAvMjAyMiAwNzoxNDowNyIsImRiX25hbWUiOiI4NTA1IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQURNSU5JU1RSQVRPUiIsImV4cCI6MjUzNDAyMzAwODAwLCJpc3MiOiJDbGFyZV9BSSIsImF1ZCI6IkNsYXJlX0FJIn0.qIdZOYyTiEut5-LTMT-BIAQHGej_nt44sm_gRtofqvU","mobile":mobile}

    body = {'messageText': 'TEXTMESSSAGE'}

    response = requests.post(url,headers=headers, data = body)

    print(response.text)

def msg(request,telephone):
    customer = Customer.objects.all().order_by(telephone)
    telephone = customer.telephone

    context = {
        'telephone': telephone
    }
    send_message_on_whatsapp(telephone)
    return render(request,'customer_profile.html',context)




def delete_page(request,pk):
    pi=Customer.objects.get(id=pk)
    pi.delete()
    import pdb
    pdb.set_trace
    return redirect('/crm')
    # return render(request,'crm_app.html')


    







# def edit_more_details(request, customer_id):
#     customer = get_customer(customer_id)
#     # obj=Contact.objects.all()

#     context = {
#         "user": request.user,
#         "crm_app": "active",
#         "customer": customer,    

#     }
#     return render(request, 'z.html', context)




#bank delails Functions


def delete_customer(request, id):
    try:
        customer = Customer.objects.get(pk=id)
        name = customer.first_name + " " + customer.last_name
        customer_to_delete = customer
        customer_to_delete.delete()
    except Customer.DoesNotExist:
        context = {
            "crm_page": "active"
        }


crm_app/templates/crm_app.html
{% extends 'crm/base.html' %} {% block page_title %} CRM
<script>
    $(document).ready(function() {
        $("#search_input").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#employee-table tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
{% endblock %} {% block content %}
<div class="content">
    <div class="container-fluid">
        <!-- Button trigger modal-->
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal_add_new_customer">
      Create +
    </button>
    <div class="container-fluid" style="overflow-x: scroll;-webkit-overflow-scrolling: touch;">
      <table class="table table-striped">
        <thead>
          <tr class="" >

            <th scope="col-sm-2">Suspect</th>
            <th scope="col-sm-2">Prospect</th>
            <th scope="col-sm-2">Approch</th>
            <th scope="col-sm-2">Negotiate</th>
            <th scope="col-sm-2">Won</th>
          </tr>
        </thead>
        <tbody>
            {% if customers %}
          <tr class=" " style="background: linear-gradient(160deg, #778899, #f5f5f5)">
        
            <td class="col-sm-2  "><div class="card " style="width:10rem; ">
                {% for suspect in customers_suspect %}
                <div class="card-body">
                  <h5 class="card-title">{{suspect}}</h5>
                  
                 

   <a href="{% url 'crm_app:edit_customer_page' suspect.id %}" style="color:inherit">
    Edit
  </a> |
                        <a href="{% url 'crm_app:customer_profile_page' suspect.id %}" style="color:inherit">
    Profile
  </a> |
           

|


 


  <a href="{% url 'crm_app:delete_customer' suspect.id %}" style="color: inherit" ... onclick="return confirm('Are you sure you want to delete customer {{customer.f_name}} {{customer.l_name}}?')">
    Delete
  </a>


                </div>
                <hr></hr>
                {% endfor %}
               
                <td class="col-sm-2  "><div class="card " style="width:10rem; ">
                    {% for prospect in customers_prospect %}
                    <div class="card-body">
                      <h5 class="card-title">{{prospect}}</h5>
                      
                      
    
    <a href="{% url 'crm_app:edit_customer_page' prospect.id %}" style="color:inherit">
        Edit
      </a> |
            <a href="{% url 'crm_app:customer_profile_page' prospect.id %}" style="color:inherit">
        Profile
      </a> |


      

      <a href="{% url 'crm_app:delete_customer' prospect.id %}" style="color: inherit" ... onclick="return confirm('Are you sure you want to delete customer {{customer.f_name}} {{customer.l_name}}?')">
        Delete
      </a>
                           
    
                    </div>
                    <hr></hr>
                    {% endfor %}


                    <td class="col-sm-2  "><div class="card " style="width:10rem; ">
                        {% for approch in customers_approch %}
                        <div class="card-body">
                          <h5 class="card-title">{{approch}}</h5>
                          
                         
        
        <a href="{% url 'crm_app:edit_customer_page' approch.id %}" style="color:inherit">
            Edit
          </a> |
            <a href="{% url 'crm_app:customer_profile_page' approch.id %}" style="color:inherit">
            Profile
          </a> |

         

          <a href="{% url 'crm_app:delete_customer' approch.id %}" style="color: inherit" ... onclick="return confirm('Are you sure you want to delete customer {{customer.f_name}} {{customer.l_name}}?')">
            Delete
          </a>
                                
      
        
                        </div>
                        <hr></hr>
                        {% endfor %}

                        <td class="col-sm-2  "><div class="card " style="width:10rem; ">
                            {% for negotiate in customers_negotiate %}
                            <div class="card-body">
                              <h5 class="card-title">{{negotiate}}</h5>
                              
                              
            
            <a href="{% url 'crm_app:edit_customer_page' negotiate.id %}" style="color:inherit">
                Edit
              </a> |
                                    <a href="{% url 'crm_app:customer_profile_page' negotiate.id %}" style="color:inherit">
                Profile
              </a> |

             

              <a href="{% url 'crm_app:delete_customer' negotiate.id %}" style="color: inherit" ... onclick="return confirm('Are you sure you want to delete customer {{customer.f_name}} {{customer.l_name}}?')">
                Delete
              </a>
                                    
       
            
                            </div>
                            <hr></hr>
                            {% endfor %}

                            <td class="col-sm-2  "><div class="card " style="width:10rem; ">
                                {% for won in customers_won %}
                                <div class="card-body">
                                  <h5 class="card-title">{{won}}</h5>
                                  
                                 
                
                <a href="{% url 'crm_app:edit_customer_page' won.id %}" style="color:inherit" >
                    Edit
                  </a> |
                                        <a href="{% url 'crm_app:customer_profile_page' won.id %}" style="color:inherit">
                    Profile
                  </a> |

                

                  <a href="{% url 'crm_app:delete_customer' won.id %}" style="color: inherit" ... onclick="return confirm('Are you sure you want to delete customer {{customer.f_name}} {{customer.l_name}}?')">
                    Delete
                  </a>
                                       
               
                
                                </div>
                                <hr></hr>
                                {% endfor %}
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>


        <!-- Modal: modalAddNewEmployee -->
        <div class="modal fade" id="modal_add_new_customer" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="overflow-y: auto !important">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <!--Header-->
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">Add Customer</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
                    </div>
                    <!--Body-->
                    <div class="modal-body">
                        <form method="POST" action="{%url 'crm_app:add_new_customer'%}"> {%csrf_token%}
                            <div class="form-group">
                                <label for="sel1">Title:</label>
                                <select class="form-control" name="title" required>
                  <option>Mr.</option>
                  <option>Miss.</option>
                  <option>Mrs.</option>
                  <option>Dr.</option>
                  <option>Prof.</option>
                  <option>Eng.</option>
                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="First name" name="first_name" required>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Last name" name="last_name" required>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Email" name="email" required>
                            </div>

                              
                            <div class="form-group">
                                <input type="number" class="form-control" placeholder="Telephone Number" name="telephone" required>
                                <div class="form-group">
                                    <label for="sel1">Gender:</label>
                                    <select class="form-control" name="gender" required>
                      <option>Male</option>
                      <option>Female</option>
                    </select>
                                </div>
                            </div>

                            
                    </div>
                    <!--Footer-->
                    <div class="modal-footer">
                        <button class="btn btn-outline-danger" type="reset">Close</button>
                        <button class="btn btn-danger" type="submit">Save</button>
                    </div>
                    </form>

                </div>
            </div>
        </div>
        <!-- Modal: modalAddNewCustomer -->

    </div>
</div>
{%endblock content%}

crm_app/templates/edit_customer.html
{% extends 'crm/base.html'%}
{% block page_title %}
Edit {{customer.first_name}}'s Bio data
{% endblock page_title%}

{% block content%}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-body">
                    <form method="POST" action="{% url 'crm_app:edit_customer' customer.id %}">
                        {%csrf_token%}
                        <div class="form-group">
                            <label>Title</label>
                            <input type="text" class="form-control" aria-describedby="emailHelp"
                                   placeholder="Enter the title" name="title" value={{customer.title}}>
                        </div>
                        <div class="form-group">
                            <label>First Name</label>
                            <input type="text" class="form-control" aria-describedby="emailHelp"
                                   placeholder="Enter first name" name="first_name" value={{customer.first_name}}>
                        </div>
                        <div class="form-group">
                            <label>Last Name</label>
                            <input type="text" class="form-control" aria-describedby="emailHelp"
                                   placeholder="Enter last name" name="last_name" name="last_name"
                                   value={{customer.last_name}}>
                        </div>
                        <div class="form-group">
                            <label>Telephone</label>
                            <input type="text" class="form-control" aria-describedby="emailHelp"
                                   placeholder="Telephonee" name="telephone" name="telephone"
                                   value={{customer.telephone}}>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" class="form-control" aria-describedby="emailHelp"
                                   placeholder="Enter last email" name="email" name="email"
                                   value={{customer.email}}>
                        </div>
                        


                     <div class="form-group">
                            <label>Status : 
                                          Suspect,
                                          Prospect,
                                          Approch,
                                          Negotiate,
                                          Won
                                       
                                        
                            </label> 
                            
                            <input type="text" class="form-control" aria-describedby="emailHelp"
                                   placeholder="status"  name="status"
                                   value={{customer.status}}>
                        </div> 

                       {% comment %} <div class="form-group">
                            <label>Status:</label>
                            <select class="form-control" placeholder="status" name="status"
                                    value="{{customer.status}}">
                                    <option value="default"></option>

                                     <option value="suspect">Suspect</option>
                                     <option value="prospect">Prospect</option>
                                     <option value="approch">Approch</option>
                                     <option value="negotiate">Negotiate</option>
                                     <option value="won">Won</option>
                           
                            </select>
                        </div>   {% endcomment %}

        
                </div>
                <!--Footer-->
                <div class="modal-footer">
                    <a href="{%url 'crm_app:customer_page' customer.id%}">
                        <button type="button"
                                class="btn btn-outline-danger">Back
                        </button>
                    </a>
                    <button class="btn btn-danger" type="submit">Save</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

crm_app/templates/failed.html
{% extends 'crm/base.html'%} {% load static %}
{% block page_title %}
Success!!
{% endblock %}


{% block content %}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3 style="padding-top:20px">{{success_msg}}</h3>
                <a href="{% url 'contact:contact_page'%}">
                    <button class="btn btn-outline-danger">Back</button>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

crm_app/templates/success.html
{% extends 'crm/base.html'%} {% load static %}
{% block page_title %}
Success!!
{% endblock %}


{% block content %}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3 style="padding-top:20px">{{success_msg}}</h3>
                <a href="{% url 'crm_app:crm_page'%}">
                    <button class="btn btn-outline-danger">Back</button>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}